[package]
name = "test_cargo"
version = "0.1.0"
authors = ["temporary"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
crossterm = "0.23.2"
rayon = "1.2.1"
